name: advstory
description: An advanced, complete story viewer. Has support for images, videos, custom widget contents, gestures, interceptors, listeners, manipulators and much more.
version: 0.3.0+2
homepage: https://advstory.sourcekod.com
repository: https://github.com/ertgrulll/advstory
issue_tracker: https://github.com/ertgrulll/advstory/issues
maintainer: Ertuğrul Yakın (@ertgrulll)

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.14.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0
  video_player: ^2.9.5
  cached_network_image: ^3.4.1
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  dartdoc:
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

flutter: